### ISSUE TITLE
DB migrations

### ISSUE THREAD

**Issue by jakubzapletal** [spapali/Blue-Economics#30]
As you sometimes change database schema, it might by useful to have some tool for managing changes/differences. There is a good tool http://phinx.org/ providing it.

If you are interested in, I can implement it and write some use case/example.

@innls @jemuelyoung @dasibre @rosebery19 @obraafo

**Comment by obraafo** [comment]
Started using propel for the FAQ Api. This comes with a migration feature, so we'll not need phinx as a separate tool. The jobs data is static and can be regenerated anytime, so migrations are not critical for that aspect of the project.

The FAQ system though will benefit from migrations since it will contain user generated data.
